### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by NineKFlames**
Add projects with Docker-in-Docker images to be used in CI.

### CODE REVIEW

**Comment by VladKopanev** [comment]
Thank you 🙏  for sharing your projects @NineKFlames ! Sorry to bother you, but could we, for now, add the libs without a "DinD:" prefix? We would rearrange those libs later when we will figure out a better way to represent this list.

**Comment by NineKFlames** [comment]
These are not libraries, but Docker-in-Docker ~containers~ images. Should I add a separate category for them or mb use `s"$techName: Docker-in-Docker"` pattern?

**Comment by VladKopanev** [comment]
Yeah, use later, please, because if we're about to add new categories, we need to decide where to put others as well, but that's out of the scope of the current issue

**Comment by NineKFlames** [comment]
Done

**Comment by VladKopanev** [comment]
LGTM, thanks 🙏

**Pull request merged**
